// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_minimum_length_to_freetext_metric : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_minimum_length_to_freetext_metric));
        
        string IMigrationMetadata.Id
        {
            get { return "201507032209070_Add_minimum_length_to_freetext_metric"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
