// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addpagetometricgroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addpagetometricgroups));
        
        string IMigrationMetadata.Id
        {
            get { return "201507101950256_Add-page-to-metric-groups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
