// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Add_multiple_answer_metric : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_multiple_answer_metric));
        
        string IMigrationMetadata.Id
        {
            get { return "201505212112102_Add_multiple_answer_metric"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
