// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_hasTimeValue_to_date_metric : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_hasTimeValue_to_date_metric));
        
        string IMigrationMetadata.Id
        {
            get { return "201707131856366_Add_hasTimeValue_to_date_metric"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
