// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_formTemplate_descriptionFormat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_formTemplate_descriptionFormat));
        
        string IMigrationMetadata.Id
        {
            get { return "201706092222340_Add_formTemplate_descriptionFormat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
