// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_created_by_to_project : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_created_by_to_project));
        
        string IMigrationMetadata.Id
        {
            get { return "201802100728027_Add_created_by_to_project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
