// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Replace_voucher_amount_with_period : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Replace_voucher_amount_with_period));
        
        string IMigrationMetadata.Id
        {
            get { return "201805151323597_Replace_voucher_amount_with_period"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
