// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_export_flags_to_assignment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_export_flags_to_assignment));
        
        string IMigrationMetadata.Id
        {
            get { return "201802100739044_Add_export_flags_to_assignment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
