// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_organizations_base_info : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_organizations_base_info));
        
        string IMigrationMetadata.Id
        {
            get { return "201904171134522_Update_organizations_base_info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
