// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_disk_space_to_subscriptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_disk_space_to_subscriptions));
        
        string IMigrationMetadata.Id
        {
            get { return "201903181037396_Add_disk_space_to_subscriptions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
