// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Update_multiple_answer_view_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_multiple_answer_view_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201506081840170_Update_multiple_answer_view_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
