// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Add_uniqueness_to_user_emails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_uniqueness_to_user_emails));
        
        string IMigrationMetadata.Id
        {
            get { return "201505210035222_Add_uniqueness_to_user_emails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
