// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Make_project_non_mandatory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Make_project_non_mandatory));
        
        string IMigrationMetadata.Id
        {
            get { return "201612050202300_Make_project_non_mandatory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
