// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Enhance_assignments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Enhance_assignments));
        
        string IMigrationMetadata.Id
        {
            get { return "201709090752228_Enhance_assignments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
