// <auto-generated />
namespace LightMethods.Survey.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fix_migration_issues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fix_migration_issues));
        
        string IMigrationMetadata.Id
        {
            get { return "201705061424528_Fix_migration_issues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
